import { MetadataRoute } from 'next';

/**
 * Sitemap for search engines
 * Automatically generated by Next.js
 * 
 * Learn more: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
 */

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://krakowtransfer.com';
  
  // Static pages
  const routes = [
    '',
    '/book/warsaw',
    '/book/katowice',
    '/book/krakow',
    '/book/wroclaw',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1.0 : 0.8,
  }));

  return routes;
}
